# Generated by Django 6.0.3 on 2026-03-30 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: F-16C Fighting Falcon', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField(help_text='Write at least 20 characters.', validators=[django.core.validators.MinLengthValidator(20)])),
                ('first_flight_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1903)])),
                ('max_speed_kmh', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='Max speed (km/h)')),
                ('crew', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active_service', models.BooleanField(default=True)),
                ('features', models.ManyToManyField(blank=True, related_name='aircraft', to='catalog.feature')),
                ('manufacturers', models.ManyToManyField(related_name='aircraft', to='catalog.manufacturer')),
                ('origin_countries', models.ManyToManyField(related_name='origin_aircraft', to='catalog.country')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='catalog.role')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
